# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_grid:
    templates:
        action:
            shop_quick_return: "@SyliusShop/Grid/Action/quickReturn.html.twig"
    grids:
        sylius_shop_account_order:
            actions:
                item:
                    quick_return:
                        type: shop_quick_return
                        label: bitbag_sylius_inpost_plugin.ui.quick_return
                        options:
                            link:
                                route: sylius_shop_account_order_return
                    
                    show:
                        type: shop_show
                        label: sylius.ui.show
                        options:
                            link:
                                route: sylius_shop_account_order_show
                                parameters:
                                    number: resource.number
                    pay:
                        type: shop_pay
                        label: sylius.ui.pay
                        options:
                            link:
                                route: sylius_shop_order_show
                                parameters:
                                    tokenValue: resource.tokenValue
        
        bitbag_admin_shipping_export:
            fields:
                order:
                    type: twig
                    label: sylius.ui.order
                    path: .
                    sortable: shipment.order
                    options:
                        template: "@BitBagSyliusShippingExportPlugin/ShippingExport/Grid/Field/orderNumber.html.twig"
                shipment:
                    type: datetime
                    label: sylius.ui.created_at
                    path: shipment.createdAt
                    sortable: shipment.createdAt
                    options:
                        format: 'd-m-Y H:i:s'
                exportedAt:
                    type: twig
                    label: bitbag.ui.exported_at
                    path: .
                    sortable: ~
                    options:
                        template: "@BitBagSyliusShippingExportPlugin/ShippingExport/Grid/Field/exportedAt.html.twig"
                shippingMethod:
                    type: twig
                    label: sylius.ui.shipping_method
                    path: .
                    sortable: shipment.method
                    options:
                        template: "@BitBagSyliusShippingExportPlugin/ShippingExport/Grid/Field/shippingMethod.html.twig"
                labelPath:
                    type: twig
                    label: bitbag.ui.shipping_export_label
                    path: .
                    sortable: ~
                    options:
                        template: "@BitBagSyliusShippingExportPlugin/ShippingExport/Grid/Field/shippingExportLabel.html.twig"
                parcel_template:
                    type: twig
                    label: bitbag_sylius_inpost_plugin.ui.parcel_template.label
                    path: .
                    sortable: ~
                    options:
                        template: "@BitBagSyliusInPostPlugin/ShippingExport/Grid/Field/parcel_template.html.twig"
                state:
                    type: twig
                    label: sylius.ui.state
                    path: .
                    sortable: ~
                    options:
                        template: "@BitBagSyliusShippingExportPlugin/ShippingExport/Grid/Field/state.html.twig"
