parameters:
    bitbag.inpost.label_type: 'normal'
    bitbag.inpost.parcel_template: 'large'
imports:
    - { resource: "@BitBagSyliusInPostPlugin/Resources/config/services.xml" }
    - { resource: "@BitBagSyliusInPostPlugin/Resources/config/resource/bitbag_inpost.yml" }
    - { resource: "@BitBagSyliusInPostPlugin/Resources/config/sylius_ui.yml" }
    - { resource: "@BitBagSyliusInPostPlugin/Resources/config/grid/*" }
twig:
    globals:
        inpost_client: '@bitbag.sylius_inpost_plugin.api.web_client'
